---
- hosts: all
  become: true
  tasks:
  - name: Update cache
    ansible.builtin.apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 package
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update cache
    ansible.builtin.dnf:
      update_cache: true
    when: ansible_distribution == "Fedora"

  - name: Install httpd package
    ansible.builtin.dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

