---
- hosts: all
  become: true
  tasks:
    
    - name: Install update for Fedora
      tags: always
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"
    
    - name : Install update for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
    - name: Install apache for web servers
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
    
    - name: Install mariadb package on db servers
      tags: fedora,db
      ansible.builtin.dnf:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "Fedora"
