- name: Install apache for web servers (Ubuntu)
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"
  when: ansible_distribution == "Ubuntu"

- name: Ensure apache is running(Ubuntu)
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin darkseid@example.org
  when: ansible_distribution == "Fedora"
  notify: restart_apache
    
- name: copy html file for site
  tags: apache, ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
